# Generated by Django 6.0.3 on 2026-07-05 15:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='phone',
            field=models.CharField(blank=True, help_text='Client phone so the developer can call', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price_agreed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final agreed price, used for revenue stats', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='progress',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='ticket',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_progress', 'In Progress'), ('review', 'In Review'), ('delivered', 'Delivered'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='TicketUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('progress', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('attachment', models.FileField(blank=True, help_text='Screenshot or video of the progress', null=True, upload_to='updates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
