# Generated by Django 6.0.3 on 2026-07-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='DevForge', max_length=100)),
                ('tagline', models.CharField(blank=True, default='Crafting Code, Building Solutions', max_length=200)),
                ('hero_title', models.CharField(default='DevForge – Crafting Code, Building Solutions', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, default="Full-stack developer & Master's student in Computer Science specializing in Mobile Networks and Embedded Systems. I build web apps, mobile apps and automation tools.")),
                ('hero_cta_text', models.CharField(default='Start a Project', max_length=100)),
                ('years_experience', models.PositiveIntegerField(default=3)),
                ('projects_completed', models.PositiveIntegerField(default=20)),
                ('happy_clients', models.PositiveIntegerField(default=10)),
                ('about_title', models.CharField(default='About Me', max_length=200)),
                ('about_text', models.TextField(blank=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('cv_file', models.FileField(blank=True, help_text='Downloadable CV / resume', null=True, upload_to='site/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('availability', models.CharField(blank=True, default='Available for freelance work', max_length=200)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('whatsapp', models.CharField(blank=True, help_text='Number with country code, e.g. +213...', max_length=50)),
                ('fiverr_url', models.URLField(blank=True)),
                ('upwork_url', models.URLField(blank=True)),
                ('footer_text', models.CharField(blank=True, default='Built with React & Django.', max_length=300)),
            ],
            options={
                'verbose_name': 'Site configuration',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('languages', 'Languages'), ('web', 'Web & Frameworks'), ('mobile', 'Mobile'), ('automation', 'Automation & Testing'), ('embedded', 'Networks & Embedded'), ('tools', 'Tools & Other')], default='tools', max_length=20)),
                ('level', models.PositiveIntegerField(default=80, help_text='Proficiency 0-100')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
